# An example plugins configuration file

target_dir = '{server_root}/plugins/'

# Simple Voice Chat
[[files]]
type = 'spiget'
resource_id = 93738
filename = 'simple-voice-chat.jar'

# SinglePlayerSleep
[[files]]
type = 'spiget'
resource_id = 68139
filename = 'single-player-sleep.jar'

# YetAnotherHeads
[[files]]
type = 'url'
url = 'https://github.com/zatrit/yah/releases/download/1.0/yah-1.0-SNAPSHOT.jar'
filename = 'yah.jar'

# GSit
[[files]]
type = 'spiget'
resource_id = 62325
filename = 'gsit.jar'

# SkinsRestorer
[[files]]
type = 'spiget'
resource_id = 2124
filename = 'skins-restorer.jar'

# Chunky
[[files]]
type = 'spiget'
resource_id = 81534
filename = 'chunky.jar'